config/routes.rb
Rails.application.routes.draw do
  root 'pokemons#index'
  resources :pokemons, only: [:index, :show, :destroy]
  get 'search', to: 'pokemons#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/pokemon_image.rb
class PokemonImage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    # Exibe todos os Pokémon armazenados localmente
    @pokemons = Pokemon.all
  end

  def show
    # Exibe detalhes de um Pokémon específico
    @pokemon = Pokemon.find(params[:id])
  end

  def search
    service = PokemonService.new
    response = service.fetch_pokemon(params[:name].downcase)
  
    if response.success?
      data = response.parsed_response
    
      # Coletar o primeiro ataque
      move_name = data['moves'][0]['move']['name'] if data['moves'].any?
      attack_response = service.fetch_move_details(move_name) if move_name
    
      if attack_response[:success]
        attack_data = attack_response[:parsed_response]
    
        @pokemon = Pokemon.create(
          name: data['name'],
          hp: data['stats'].find { |stat| stat['stat']['name'] == 'hp' }['base_stat'],
          pokemon_type: data['types'][0]['type']['name'],
          height: data['height'],
          weight: data['weight'],
          abilities: data['abilities'].map { |a| a['ability']['name'] }.join(", "),
          image_url: data['sprites']['front_default'],
          name_attack: attack_data['name'],
          base_damage: attack_data['power'], 
          attack_type: attack_data['type']['name'], 
          effect: attack_data['effect_entries'][0]['effect'],
          
        )
      else
        flash[:alert] = "Detalhes do ataque não encontrados!"
      end
    else
      flash[:alert] = "Pokémon não encontrado!"
    end
    
  end  

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pokedex" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <script>
      document.addEventListener("DOMContentLoaded", function() {
        const buttons = document.querySelectorAll("form[data-confirm]");

        buttons.forEach(button => {
          button.addEventListener("submit", function(event) {
            const message = button.getAttribute("data-confirm");
            if (!confirm(message)) {
              event.preventDefault();
            }
          });
        });
      });
    </script>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1>Pokédex</h1>
<%= form_with url: search_path, method: :get, local: true do |form| %>
  <%= form.text_field :name, placeholder: "Digite o nome do Pokémon" %>
  <%= form.submit "Buscar" %>
<% end %>

<ul>
  <% @pokemons.each do |pokemon| %>
    <li><%= link_to pokemon.name.capitalize, pokemon_path(pokemon) %></li>
  <% end %>
</ul>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name.capitalize %></h1>
<p><strong>Tipo:</strong> <%= @pokemon.pokemon_type.capitalize %></p>
<p><strong>Altura:</strong> <%= @pokemon.height / 10 %> m</p> <!-- Convertendo dm para m -->
<p><strong>Peso:</strong> <%= @pokemon.weight / 10 %> kg</p> <!-- Convertendo hg para kg -->
<p><strong>Habilidades:</strong> <%= @pokemon.abilities %></p>
<p><strong>HP:</strong> <%= @pokemon.hp %></p> <!-- Exibindo o HP -->

<% if @pokemon.image_url.present? %>
  <p><img src="<%= @pokemon.image_url %>" alt="<%= @pokemon.name %> image" class="pokemon-image"></p>
<% else %>
  <p>No image available</p>
<% end %>

<h2>Informações do Ataque</h2>
<p><strong>Nome do Ataque:</strong> <%= @pokemon.name_attack || 'N/A' %></p>
<p><strong>Dano Base:</strong> <%= @pokemon.base_damage || 'N/A' %></p>
<p><strong>Tipo do Ataque:</strong> <%= @pokemon.attack_type || 'N/A' %></p>
<p><strong>Efeito do Ataque:</strong> <%= @pokemon.effect || 'N/A' %></p>

<p>
  <%= button_to 'Erase Pokémon', pokemon_path(@pokemon), method: :delete, class: 'btn-delete', data: { confirm: 'Are you sure you want to delete this Pokémon?' } %>
  <%= link_to 'Return', root_path, class: "btn btn-secondary" %>
</p>